import { chromium } from "playwright";
import { mkdir } from "node:fs/promises";
import { resolve } from "node:path";

const output = resolve("test-results/visual");
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
const page = await context.newPage();
await page.goto("http://127.0.0.1:3100/login");
await page.getByLabel("Work email").fill("mihar@fhqtc.net");
await page.getByLabel("Password").fill("fhqtechdemo");
await page.getByRole("button", { name: "Sign in", exact: true }).click();
await page.waitForURL(/dashboard/);
await page.screenshot({ path: resolve(output, "dashboard-desktop.png"), fullPage: true });
await page.goto("http://127.0.0.1:3100/tickets/1048");
await page.screenshot({ path: resolve(output, "ticket-desktop.png"), fullPage: true });
await context.close();
const mobile = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1 });
const mobilePage = await mobile.newPage();
await mobilePage.goto("http://127.0.0.1:3100/login");
await mobilePage.getByLabel("Work email").fill("mihar@fhqtc.net");
await mobilePage.getByLabel("Password").fill("fhqtechdemo");
await mobilePage.getByRole("button", { name: "Sign in", exact: true }).click();
await mobilePage.waitForURL(/dashboard/);
await mobilePage.goto("http://127.0.0.1:3100/tickets");
await mobilePage.screenshot({ path: resolve(output, "queue-mobile.png"), fullPage: true });
await mobile.close();
await browser.close();
console.log(output);
